apiVersion: skaffold/v2beta22
kind: Config
build:
  artifacts:
  - image: piomin/sample-spring-kotlin-microservice
    jib: {}
deploy:
  helm:
    releases:
      - name: sample-spring-kotlin-microservice
        chartPath: chart
        valuesFiles:
          - chart/values.yaml
        artifactOverrides:
          image: piomin/sample-spring-kotlin-microservice
        imageStrategy:
          helm: {}
