spring:
  application:
    name: sample-spring-kotlin-microservice
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/postgres
    username: postgres
    password: postgres123
    hikari:
      connection-timeout: 2000
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    connection-timeout: 2000
management:
  endpoints.web.exposure.include: '*'
  endpoint:
    health:
      show-details: always # optionally - just for information

property1: 123