spring:
  application:
    name: sample-spring-kotlin-microservice
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    hikari:
      connection-timeout: 2000
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5762
    connection-timeout: 2000
management:
  endpoints.web.exposure.include: '*'
  endpoint:
    health:
      show-details: always # optionally - just for information

property1: 123
